"""Significado concreto de alternativas equivocadas en reconstrucciones literales."""
DISTRACTOR_MEANINGS={
'consejo de estado':'órgano consultivo del Gobierno, no la institución parlamentaria',
'tribunal supremo':'órgano jurisdiccional superior, distinto de las Cortes Generales',
'tribunal superior de justicia':'órgano judicial del ámbito autonómico, distinto de los organismos de igualdad o del ámbito audiovisual',
'secretariado':'unidad de secretaría o apoyo, distinta del observatorio o registro citado',
'tribunal':'órgano que ejerce función jurisdiccional, distinta del seguimiento o registro del pasaje',
'acta de arqueo':'constancia de un recuento de fondos, distinta de analizar los efectos sobre la igualdad',
'acto de trámite':'actuación dentro de un procedimiento, distinta de una condición del puesto o un daño laboral',
'agrupados sólo por municipio':'agrupación territorial que no separa los datos de mujeres y hombres',
'antigüedad':'tiempo transcurrido, distinto de la reserva de la intimidad o la difusión de información',
'antigüedad documental':'edad de los documentos, que no mide el impacto sobre mujeres y hombres ni la posibilidad o gravedad de un daño',
'antigüedad exclusivamente':'únicamente tiempo de servicio, dejando fuera la seguridad y la salud del puesto',
'antigüedad tributaria':'tiempo referido al ámbito de los tributos, distinto de la situación de maternidad',
'asistencia exclusivamente mercantil':'atención limitada a relaciones comerciales, excluyendo el apoyo social integral de la regla',
'asistencia exclusivamente tributaria':'atención limitada a impuestos, excluyendo el apoyo social integral de la regla',
'asistencia sólo documental':'atención limitada a documentos, excluyendo las prestaciones del apoyo social integral',
'autonomía organizativa':'capacidad de organizarse, distinta de la ausencia de discriminación o la certeza jurídica',
'catastro exclusivamente':'actividad limitada al inventario catastral, distinta de las medidas de empleo',
'certificación catastral':'acreditación de datos del Catastro, distinta de asesoramiento y defensa jurídica',
'colegios profesionales exclusivamente':'limitación a corporaciones profesionales, excluyendo las Administraciones a las que se dirige el precepto',
'competencia territorial':'ámbito geográfico en que puede actuar un órgano, distinto de la capacidad económica',
'competitividad':'capacidad de competir, distinta de compartir responsabilidades o de una relación de dependencia',
'compulsas':'cotejo de una copia con su original, distinto de notificar o publicar un acto',
'conciliación laboral':'compatibilización de vida laboral y personal, distinta de las conductas de acoso o la negociación colectiva',
'confiscación':'privación de bienes, distinta de permitir el acceso, la participación o describir una exclusión',
'consentimiento de tercero no autorizado':'permiso dado por alguien que carece de autorización, distinto de una decisión judicial',
'contratación mercantil exclusivamente':'actuación limitada a contratos comerciales, distinta de la política de vivienda del artículo',
'criterio de antigüedad':'prioridad según tiempo transcurrido, distinta del análisis de desigualdades entre mujeres y hombres',
'daño ya consumado':'lesión que ya se ha producido, mientras que el riesgo describe la posibilidad de un daño',
'decisión de empresa privada':'decisión empresarial, distinta de la resolución del órgano judicial exigida en el pasaje',
'densidad urbana':'concentración de población o edificación, distinta del efecto de una medida sobre la igualdad entre mujeres y hombres',
'derecho a herencia':'derecho ligado a la sucesión de bienes, distinto de formular peticiones',
'derecho de propiedad':'derecho sobre bienes, distinto de dirigir peticiones por escrito',
'derecho máximo negociable':'un límite máximo modificable por negociación, que contradice una garantía mínima indisponible',
'difusión obligatoria':'mandato de divulgar la información, que contradice la reserva exigida por la confidencialidad',
'documento de constancia':'documento que acredita hechos, distinto de una característica del puesto o una lesión laboral',
'documento de decisión':'documento que expresa una decisión, distinto de una máquina de trabajo o un equipo protector',
'elección unánime':'acuerdo de todas las personas en una elección, distinto del equilibrio de representación por sexo',
'entidades exclusivamente privadas':'limitación a entidades privadas, que excluye a las Administraciones destinatarias del precepto',
'entidades sin personalidad exclusivamente':'limitación a entidades sin personalidad jurídica, que no identifica a las personas individuales',
'estabilidad presupuestaria':'equilibrio del presupuesto, distinto de igualdad de oportunidades o libertad de actividad empresarial',
'estado civil exclusivamente':'limitación a la condición matrimonial, distinta de la situación de embarazo',
'evaluación tributaria':'análisis de cuestiones fiscales, distinto del modelo educativo de igualdad',
'excepcionalmente opcional':'posibilidad de elegir sólo excepcionalmente, distinta del carácter obligatorio o voluntario que fija el artículo',
'exclusividad':'reserva a una sola persona o colectivo, distinta de compartir responsabilidades o permitir el acceso',
'expropiaciones':'privaciones de bienes mediante el procedimiento correspondiente, distintas de datos estadísticos, sanciones o decisiones judiciales',
'expropiación':'privación de bienes mediante el procedimiento correspondiente, distinta de la actuación educativa, preventiva, formativa o de conciliación de la frase',
'fiscalización tributaria':'control del cumplimiento fiscal, distinto de la adquisición de formación',
'identificación pública de víctimas':'divulgación de la identidad de las víctimas, que contradice la confidencialidad',
'informe de tesorería':'análisis de cuestiones de cobros, pagos o fondos, distinto del efecto de una medida sobre la igualdad',
'inspección patrimonial':'comprobación de bienes o patrimonio, distinta de la asistencia jurídica',
'inspección tributaria':'comprobación fiscal, distinta de la actuación cultural del artículo',
'interés recaudatorio':'finalidad de obtener ingresos, distinta de considerar las desigualdades por género',
'inventario de bienes':'relación de bienes, distinta de analizar el efecto de una medida sobre mujeres y hombres',
'inventario patrimonial':'relación del patrimonio, distinta del instrumento de medidas de igualdad',
'jerarquización':'orden por niveles o rangos, distinto de eliminar barreras de acceso',
'ley ordinaria':'tipo de ley distinto de la ley orgánica expresamente exigida para esta materia',
'mayoría de dos tercios':'umbral de votos de dos tercios, distinto de equilibrar la representación de mujeres y hombres',
'medios exclusivamente impresos':'limitación al soporte impreso, que elimina los medios electrónicos de la regla',
'medios exclusivamente telefónicos':'limitación a llamadas, que no equivale a la actuación por medios electrónicos prevista en la frase',
'medios exclusivamente verbales':'limitación a comunicación oral, que elimina la vía electrónica prevista en la frase',
'normativa exclusivamente voluntaria':'reglas cuya observancia dependería de voluntad, que contradice el mínimo obligatorio e indisponible',
'número de oficinas':'recuento de dependencias, que no mide la gravedad del daño',
'número de registros':'recuento de anotaciones, que no define la posibilidad de que se produzca el daño',
'orden ministerial':'disposición dictada por un ministerio, de rango distinto de la ley orgánica exigida',
'orden verbal policial':'instrucción oral de la policía, distinta de la decisión de un órgano judicial',
'ordenación registral':'organización de registros, distinta de educación para la igualdad',
'ordenados por antigüedad exclusivamente':'ordenación por edad o fecha que no separa los datos según sexo',
'padrón de habitantes':'registro municipal de residentes, distinto del registro de documentos o del archivo histórico',
'patrimonio exclusivamente':'actuación limitada a bienes, que excluye la materia de empleo prevista',
'personas jurídicas exclusivamente':'limitación a entidades con personalidad jurídica, distinta de las personas individuales',
'planes de archivo':'organización de documentación y archivos, distinta de un conjunto de medidas de igualdad',
'planes de recaudación':'organización de la obtención de ingresos, distinta de un conjunto de medidas de igualdad',
'planes de urbanismo':'planificación urbanística, distinta de un conjunto de medidas de igualdad',
'presunción de antigüedad':'suposición acerca del tiempo transcurrido, distinta de la garantía de no anticipar culpabilidad',
'presunción de culpabilidad':'atribución anticipada de culpa, contraria a la presunción de inocencia',
'presunción de unanimidad':'suposición de acuerdo de todas las personas, distinta de la garantía de inocencia',
'presupuesto general':'previsión de ingresos y gastos, distinta del plan de medidas de igualdad',
'prioridad presupuestaria':'preferencia basada en el presupuesto, distinta de considerar las desigualdades por género',
'proceso civil':'procedimiento ante órganos judiciales del orden civil, distinto del cauce administrativo citado',
'proceso laboral':'procedimiento ante órganos judiciales del ámbito laboral, distinto del cauce administrativo citado',
'proceso penal':'procedimiento judicial penal, distinto del cauce administrativo citado',
'productividad exclusivamente':'consideración sólo del rendimiento, que deja fuera la seguridad y salud',
'prohibido':'carácter no permitido, opuesto al deber de realizar lo que el precepto declara obligatorio',
'propiedad inmobiliaria':'titularidad de inmuebles, distinta de la situación de maternidad',
'propiedad intelectual exclusivamente':'limitación a derechos sobre creaciones, distinta de la política de vivienda',
'protección del patrimonio':'preservación de bienes, distinta de la igualdad de oportunidades o libertad de empresa',
'protección documental':'conservación o reserva de documentos, distinta de proteger al conjunto de trabajadores frente al riesgo',
'protección patrimonial':'preservación de bienes, distinta de la protección preventiva del conjunto de personas',
'publicidad indiscriminada':'divulgación sin restricción, contraria a mantener información reservada',
'rango administrativo':'nivel jerárquico en la Administración, distinto de la situación de maternidad',
'rango jerárquico':'posición en una jerarquía, distinta del efecto de género, el embarazo o la medición del riesgo',
'recargo tributario':'incremento de una obligación fiscal, distinto de la situación de embarazo',
'recaudación':'obtención de ingresos, distinta de la actuación educativa, cultural, preventiva o de protección que fija esta frase',
'recaudación exclusivamente':'consideración sólo de ingresos, que deja fuera la seguridad y salud',
'recaudación tributaria':'obtención de ingresos fiscales, distinta de asesoramiento y defensa jurídica',
'recomendación sin efectos':'consejo sin obligatoriedad, contrario a una garantía mínima obligatoria e indisponible',
'recurso de casación':'recurso judicial, distinto del recurso administrativo de alzada',
'recurso de reposición':'recurso administrativo ante el órgano que dictó el acto, distinto de alzada ante su superior',
'registro exclusivamente manual':'limitación a anotaciones manuales, distinta del registro electrónico o del archivo histórico',
'registro mercantil':'registro referido a empresas y actos mercantiles, distinto de la actuación cultural',
'reglamento municipal':'disposición reglamentaria local, de rango distinto de la ley orgánica exigida',
'reglamento tributario':'regulación de tributos, distinta del plan de igualdad',
'representación exclusiva':'reserva de representación a un grupo, distinta de equilibrar la presencia de mujeres y hombres',
'restringirá':'mandato de limitar la actuación, distinto de fomentarla',
'riesgo exclusivamente remoto':'posibilidad lejana, que contradice la materialización probable en un futuro inmediato',
'riesgo necesariamente leve':'riesgo de daño leve, que contradice la gravedad exigida al riesgo grave e inminente',
'sanción exclusivamente':'actuación limitada a penalizar infracciones, distinta de las medidas de empleo',
'segregación obligatoria':'separación impuesta, distinta de educar conjuntamente para superar estereotipos sexistas',
'servicio mercantil exclusivamente':'limitación a una actividad comercial, que excluye el carácter de servicio público de la frase',
'servicio privado exclusivamente':'limitación al ámbito privado, que excluye el carácter público expresamente indicado',
'servicio voluntario sin regulación':'actividad dejada enteramente a voluntad y sin reglas, distinta del servicio público regulado',
'sin clasificación alguna':'ausencia de separación de datos, que impide la desagregación por sexo prevista',
'sucesión patrimonial':'transmisión de bienes por sucesión, distinta de la situación de lactancia',
'tesorería':'ámbito de cobros, pagos y fondos, distinto de salud, deporte o patrimonio',
'tributación':'ámbito de obligaciones fiscales, distinto de la política de vivienda',
'urbanismo exclusivamente':'limitación a ordenación urbana, distinta de salud o del patrimonio citado',
'órgano consultivo':'órgano que asesora, distinto de una máquina de trabajo o un equipo protector',
'órganos colegiados exclusivamente':'limitación a órganos de varias personas, que no identifica a las personas físicas',
'órganos judiciales exclusivamente':'limitación a los órganos jurisdiccionales, que excluye a las Administraciones destinatarias de la regla',
}
